### PR TITLE
Improve documentation on -o function

### PR DESCRIPTION
**Pull request by Jeroen6**
I think this is a start.

### CODE REVIEW

**Review by AlphaSierraHotel — CHANGES_REQUESTED** [review]
We shouldn't be referencing the escaped % symbols (as in doubling them: '%%').  They aren't needed from the command line generally and are only needed when the command interpreter being used is trying to expand them itself.

**Comment by Jeroen6** [comment]
I also encountered the escaping difference between cmd and powershell. Didn’t pay attention to it if I’m honest.

What if -o without any arguments behaves like ‘-o “%%”’?

**Comment by AlphaSierraHotel** [comment]
That would be adding functionality & complexity that I'm not sure is needed.  I feel that the user ought to be responsible for specifying a filename or pattern of some sort before we go ahead and create it.

Are there any other documentation updates that you feel would be appropriate to this commit?

**Review by AlphaSierraHotel — APPROVED** [review]

**Review by tbird20d — APPROVED** [review]
This looks good.  The double-percents were needed, I believe, when I was using string formatting on the usage string, in order to output a single percent.  Since I no longer do string formatting, the extra leading percent sign is not needed as an escape value.

**Comment by Jeroen6** [comment]
No I think this explains it enough. 
I was initially put on the wrong path by the `includes` and didn't notice the option to use the strftime strings. 
This is now covered.

**Pull request merged**
